export default {
    "de": {
        "dialogue": {
            "stepLabel": "Schritt {{current}} von {{total}}",
            "headerTitle": "Besprochen...",
            "headerSubtitle": "Dokumentiere die Essenz deines Dialogs",
            "headerSubtitle2": "Wähle alle Themen, die im Dialog\nerwähnt wurden",
            "initiativeMatching": "Selbst aktiv werden",
            "selectInterests": "Entdecke konkrete Möglichkeiten, etwas zu verändem",
            "notesLabel": "Notizen",
            "notesPlaceholder": "Was ist das Interesse des\nDialogpartners\nWas macht für dich eine lebenswerte\nstadt aus?",
            "recordAudio": "Nimm Audio auf",
            "skip": "überspringen",
            "back": "Zurück",
            "next": "Weiter",
            "continue": "Weiter",
            "newDialogue": "Neuer Dialog"
        },
        "welcome": {
            "title": "Sag doch mal, Berlin",
            "subtitle": "Bürger:innen Dialog dokumentiere zu gesellschaftsrelevanten Theme",
            "startButton": "Starte den Dialog",
            "caredBy": "cared for by Generation iTrust",
            "tagline": "Hören, Reden, Mitgestalten"
        },
        "login": {
            "welcomeBack": "Willkommen zurück",
            "pleaseSignIn": "Bitte melde dich an, um fortzufahren.",
            "username": "Username",
            "password": "Password",
            "loginButton": "Login"
        },
        "districts": {
            "selectDistrict": "Bezirk auswählen"
        },
        "topics": {
            "housingBuildingTransition": "Wohnen/Bauwende",
            "housingHeatTransition": "Wohnen/Wärmewende",
            "mobility": "Mobilität",
            "climateAdaptation": "Klimaanpassung",
            "otherNotes": "Sonstiges/Notizen",
            "transport": "Verkehr",
            "costs": "Kosten",
            "electricCar": "Elektroauto",
            "bicycle": "Fahrrad",
            "parking": "Parken",
            "publicTransport": "Öffentlicher Nahverkehr (ÖPNV)",
            "health": "Gesundheit (Unfälle, Luftqualität)",
            "buildingTransition": "Bauwende",
            "concrete": "Beton",
            "waste": "Abfall",
            "rent": "Miete",
            "existingStock": "Bestand",
            "community": "Gemeinschaft",
            "qualityOfLife": "Lebensqualität",
            "displacement": "Verdrängung",
            "wood": "Holz",
            "heatingTransition": "Wärmewende",
            "techOpenness": "Technologieoffenheit",
            "uneconomical": "Wirtschaftlich nicht tragfähig",
            "rentIncrease": "Mieterhöhung",
            "monumentProtection": "Denkmalschutz",
            "districtHeating": "Fernwärme",
            "oldBuilding": "Altbau",
            "homeownership": "Wohneigentum",
            "heat": "Hitze",
            "heavyRain": "Starkregen",
            "trees": "Bäume"
        },
        "initiatives": {
            "initiatives": "Initiativen",
            "initiativeMatching": "Initiativen-Matching",
            "selectInterestAreas": "Interessensgebiete auswählen",
            "findInitiatives": "Initiativen finden",
            "changeInterests": "Interessen ändern",
            "relevantInitiatives": "Relevante Initiativen",
            "in": "in",
            "qrCode": "QR Code",
            "noInitiativesMatch": "Keine Initiativen entsprechen den aktuellen Filtern.",
            "preparingQR": "QR wird vorbereitet...",
            "showQR": "QR anzeigen",
            "scanForMoreInfo": "Für weitere Informationen scannen",
            "close": "Schließen",
            "urbanGardening": "Urban Gardening/Stadtgärtnern",
            "communityGarden": "Gartengemeinschaft & - eigenverantwortung",
            "repairCafe": "Repair Café",
            "fixThingsTogether": "Gemeinsam reparieren, Abfall reduzieren",
            "climateEducation": "Klimabildung",
            "learnAndTeach": "Klimaschutz lernen und vermitteln",
            "policyAdvocacy": "Politische Interessenvertretung",
            "influencePolicies": "Lokale und nationale Politik beeinflussen",
            "mutualAid": "Solidarische Hilfe",
            "communitySupport": "Nachbarschaftshilfe und Solidarität",
            "digitalInclusion": "Digitale Inklusion",
            "bridgeDigitalDivide": "Digitale Kluft überbrücken"
        },
        "consent": {
            "dataConsent": "Dateneinwilligung",
            "stayInTouch": "In Kontakt bleiben",
            "stayUpToDate": "Bleib auf dem Laufenden – verbinde dich mit Initiativen",
            "shareContact": "Kontakt teilen",
            "whichContactDetails": "Welche Kontaktdaten möchtest du teilen?",
            "firstName": "Vorname",
            "lastName": "Nachname",
            "telephone": "Telefon",
            "stayAnonymous": "Anonym bleiben",
            "privacyProtected": "Deine Privatsphäre ist geschützt. Es werden nur Dialogdaten mit ausdrücklicher Zustimmung gespeichert.",
            "confidentialInfo": "Deine Angaben bleiben vertraulich und werden ausschließlich dazu genutzt, dich über lokale Initiativen zu informieren, die dich interessieren.",
            "organizationQRCode": "Organisation QR Code"
        },
        "reflection": {
            "observerReflection": "Beobachter-Reflexion",
            "yourReflection": "Deine Reflexion",
            "whatElseShowed": "Was hat dir der Dialog noch gezeigt",
            "shareThoughts": "Teile deine Gedanken zu diesem Gespräch – was hat dich überrascht oder was möchtest du dir merken?",
            "resonanceEssence": "Resonanz, Essenz, Takeaway…",
            "audioRecording": "… oder mach eine Audioaufnahme",
            "connectContexts": "mit größeren Zusammenhängen zu verknüpfen"
        },
        "metrics": {
            "observerReflectionsMetrics": "Beobachter-Reflexionsmetriken",
            "dialogue": "Dialog",
            "generalInformation": "Allgemeine Infos",
            "dialoguePartners": "Dialogpartner:innen",
            "duration": "Dauer (Min.)",
            "single": "Einzelperson",
            "family": "Familie",
            "couple": "Paar",
            "location": "Standort"
        },
        "summary": {
            "summary": "Zusammenfassung",
            "ourQRCode": "Unser QR Code"
        },
        "analytics": {
            "analyticsDashboard": "Analyse-Dashboard",
            "totalDialogues": "Gesamtanzahl Dialoge",
            "totalParticipants": "Gesamtanzahl Teilnehmende",
            "avgDuration": "Durchschn. Dauer (Min.)",
            "topDiscussedTopics": "Meistdiskutierte Themen",
            "dialoguesPerDistrict": "Dialoge pro Bezirk",
            "topInterestAreas": "Top-Interessensgebiete",
            "topSelectedIssues": "Meistgewählte Themen",
            "initiativeEngagement": "Initiativen-Beteiligung",
            "initiativeEngagementDetails": "Initiativen-Beteiligung Details",
            "recommended": "Empfohlen",
            "selected": "Ausgewählt",
            "engagementRate": "Beteiligungsrate"
        },
        "thankYou": {
            "thankYou": "Vielen Dank!",
            "responseRecorded": "Ihre Antwort wurde aufgezeichnet und wird zu Erkenntnissen über die Gemeinschaft beitragen.",
            "nextDialogue": "Nächster Dialog"
        },
        "common": {
            "soon": "Soon"
        }
    },
    "en": {
        "dialogue": {
            "stepLabel": "Step {{current}} of {{total}}",
            "headerTitle": "Discussed",
            "headerSubtitle": "Document the essence of your dialogue",
            "headerSubtitle2": "Select all topics that were\nmentioned in the dialogue",
            "initiativeMatching": "Become active yourself",
            "selectInterests": "Discover concrete possibilities to change something",
            "notesLabel": "Notes",
            "notesPlaceholder": "What is the dialogue partner's\ninterest?\nWhat makes a city worth living in\nfor you?",
            "recordAudio": "Record audio",
            "skip": "skip",
            "back": "Back",
            "next": "Next",
            "continue": "Continue",
            "newDialogue": "New Dialogue"
        },
        "welcome": {
            "title": "Yo, speak up, Berlin",
            "subtitle": "Citizen dialogue documentation on socially relevant themes",
            "startButton": "Start the dialogue",
            "caredBy": "cared for by Generation iTrust",
            "tagline": "Listen. Talk. Co-create"
        },
        "login": {
            "welcomeBack": "Welcome back",
            "pleaseSignIn": "Please sign in to continue.",
            "username": "Username",
            "password": "Password",
            "loginButton": "Login"
        },
        "districts": {
            "selectDistrict": "Select District"
        },
        "topics": {
            "housingBuildingTransition": "Housing / Building Transition",
            "housingHeatTransition": "Housing / Heat Transition",
            "mobility": "Mobility",
            "climateAdaptation": "Climate Adaptation",
            "otherNotes": "Other/Notes",
            "transport": "Transport",
            "costs": "Costs",
            "electricCar": "Electric Car",
            "bicycle": "Bicycle",
            "parking": "Parking",
            "publicTransport": "Public Transport (ÖPNV)",
            "health": "Health (Accidents, Air Quality)",
            "buildingTransition": "Building Transition",
            "concrete": "Concrete",
            "waste": "Waste",
            "rent": "Rent",
            "existingStock": "Existing Stock",
            "community": "Community",
            "qualityOfLife": "Quality of Life",
            "displacement": "Displacement",
            "wood": "Wood",
            "heatingTransition": "Heating Transition",
            "techOpenness": "Openness to Technology",
            "uneconomical": "Economically Unviable",
            "rentIncrease": "Rent Increase",
            "monumentProtection": "Monument Protection",
            "districtHeating": "District Heating",
            "oldBuilding": "Old Building",
            "homeownership": "Home Ownership",
            "heat": "Heat",
            "heavyRain": "Heavy Rain",
            "trees": "Trees"
        },
        "initiatives": {
            "initiatives": "Initiatives",
            "initiativeMatching": "Initiative Matching",
            "selectInterestAreas": "Select Interest Areas",
            "findInitiatives": "Find Initiatives",
            "changeInterests": "Change Interests",
            "relevantInitiatives": "Relevant Initiatives",
            "in": "in",
            "qrCode": "QR Code",
            "noInitiativesMatch": "No initiatives match the current filters.",
            "preparingQR": "Preparing QR...",
            "showQR": "Show QR",
            "scanForMoreInfo": "Scan for more info",
            "close": "Close",
            "urbanGardening": "Urban Gardening",
            "communityGarden": "Community garden & community sovereignity",
            "repairCafe": "Repair Café",
            "fixThingsTogether": "Fix things together, reduce waste",
            "climateEducation": "Climate Education",
            "learnAndTeach": "Learn and teach climate action",
            "policyAdvocacy": "Policy Advocacy",
            "influencePolicies": "Influence local and regional policies",
            "mutualAid": "Mutual Aid",
            "communitySupport": "Community Support and solidarity",
            "digitalInclusion": "Digital Inclusion",
            "bridgeDigitalDivide": "Bridge the digital divide"
        },
        "consent": {
            "dataConsent": "Data Consent",
            "stayInTouch": "Stay In touch",
            "stayUpToDate": "Stay up to date – connect with initiatives",
            "shareContact": "Share Contact",
            "whichContactDetails": "Which contact details would you like to share?",
            "firstName": "First Name",
            "lastName": "Last Name",
            "telephone": "Telephone",
            "stayAnonymous": "Stay Anonymous",
            "privacyProtected": "Your privacy is protected. Dialogue data will only be stored with your explicit consent.",
            "confidentialInfo": "Your information remains confidential. Your contact details will only be used to keep in touch and inform you about local initiatives that may be of interest to you.",
            "organizationQRCode": "Organization QR Code"
        },
        "reflection": {
            "observerReflection": "Observer Reflection",
            "yourReflection": "Your Reflection",
            "whatElseShowed": "What else did the dialogue show you",
            "shareThoughts": "Share your thoughts about this conversation – what surprised you or what would you like to remember?",
            "resonanceEssence": "Resonance, essence, takeaway…",
            "audioRecording": "… or make an audio recording",
            "connectContexts": "to connect with larger contexts"
        },
        "metrics": {
            "observerReflectionsMetrics": "Observer Reflections Metrics",
            "dialogue": "Dialogue",
            "generalInformation": "General Information",
            "dialoguePartners": "Dialogue Partners",
            "duration": "Duration (min)",
            "single": "Single",
            "family": "Family",
            "couple": "Couple",
            "location": "Location"
        },
        "summary": {
            "summary": "Summary",
            "ourQRCode": "Our QR Code"
        },
        "analytics": {
            "analyticsDashboard": "Analytics Dashboard",
            "totalDialogues": "Total Dialogues",
            "totalParticipants": "Total Participants",
            "avgDuration": "Avg. Duration (min)",
            "topDiscussedTopics": "Top Discussed Topics",
            "dialoguesPerDistrict": "Dialogues per District",
            "topInterestAreas": "Top Interest Areas",
            "topSelectedIssues": "Top Selected Issues",
            "initiativeEngagement": "Initiative Engagement",
            "initiativeEngagementDetails": "Initiative Engagement Details",
            "recommended": "Recommended",
            "selected": "Selected",
            "engagementRate": "Engagement Rate"
        },
        "thankYou": {
            "thankYou": "Thank you very much",
            "responseRecorded": "Your response has been recorded and will contribute to community insights.",
            "nextDialogue": "Next Dialogue"
        },
        "common": {
            "soon": "Soon"
        }
    }
};